const { createStyledEmbed, formatCodePills, getBannerFiles } = require('../utils/embedBuilder');
const emojis = require('../utils/emojis');

module.exports = {
  name: 'priority',
  description: 'AI-powered assistant for fast text, question answering, and code generation',
  aliases: ['ai', 'ask', 'code'],

  async execute(message, args) {
    const sub = args[0] ? args[0].toLowerCase() : null;
    const files = getBannerFiles();

    let clientUser = message.client.user;
    try {
      clientUser = await message.client.users.fetch(message.client.user.id, { force: true });
    } catch (e) {}

    if (!sub || sub === 'help') {
      const commandsList = [
        '.priority ask <question>',
        '.priority code <task>'
      ];

      const embed = createStyledEmbed({
        title: 'Naruto One Help Menu',
        subtitle: `${emojis.PRIORITY} Playing: Priority (AI Assistant)`,
        description: `**What Priority Can Do**\n` +
          `• Answer normal questions\n` +
          `• Describe the bot and its key links when asked\n` +
          `• Help with simple coding and debugging\n` +
          `• Act as the built-in assistant made by Priority Development\n` +
          `• Generate fast text and code replies with AI\n\n` +
          `**Commands**\n` + formatCodePills(commandsList),
        requestedBy: message.author,
        clientUser,
        footerText: 'AI overview'
      });

      return message.channel.send({ embeds: [embed], files });
    }

    const query = args.slice(1).join(' ');
    if (!query) {
      return message.reply(`⚠️ Please provide a prompt or question! Example: \`.priority ${sub} How do Ninjutsu work?\``);
    }

    const waitingMsg = await message.reply(`${emojis.SHINOBI} *Summoning Sage AI wisdom...*`);

    let aiReply = '';
    if (sub === 'ask') {
      aiReply = `**Question:** ${query}\n\n` +
        `**Sage Intelligence Response:**\n` +
        `Greetings! In response to your inquiry regarding "*${query}*":\n\n` +
        `Naruto One AI integrates advanced chakra logic with fast response algorithms. ` +
        `Always ensure your chakra reserves remain balanced whether formulating shinobi tactics or configuring server automations!`;
    } else if (sub === 'code') {
      aiReply = `**Code Task:** \`${query}\`\n\n` +
        `\`\`\`js\n` +
        `// Generated by Naruto One Priority Code AI\n` +
        `function executeTask() {\n` +
        `    console.log("Executing task: ${query}");\n` +
        `    const chakraLevel = 9000;\n` +
        `    return { status: "Success", chakra: chakraLevel };\n` +
        `}\n` +
        `module.exports = executeTask;\n` +
        `\`\`\``;
    } else {
      return waitingMsg.edit('Unknown priority command option. Use `.priority help`.');
    }

    const embed = createStyledEmbed({
      title: 'Priority AI Assistant',
      subtitle: sub === 'ask' ? `${emojis.AI_ANSWER} AI Answer` : `${emojis.AI_CODE} Generated Code Solution`,
      description: aiReply,
      requestedBy: message.author,
      clientUser,
      footerText: 'Powered by Naruto One Priority AI'
    });

    return waitingMsg.edit({ content: ' ', embeds: [embed], files });
  }
};
