/**
 * Universal Standard Unicode Emoji Registry for Naruto Bot
 * Uses clean, 100% universal standard Unicode emojis for zero-error compatibility.
 */

module.exports = {
  // --- GENERAL & BRANDING ---
  NARUTO: '🍥',
  SCROLL: '📜',
  BULB: '💡',
  QUESTION: '❓',
  OWNER_CROWN: '👑',
  MODMAIL_ENVELOPE: '📬',
  ANALYTICS_ZAP: '⚡',
  DOT: '🔸',
  DANCE: '💃',
  QUICK_LINKS: '🔗',
  EMOTES: '🎭',
  ACTIONS: '⚙️',
  PREMIUM: '💎',
  LOCK: '🔒',
  PRIZE_1: '🥇',
  PRIZE_2: '🥈',
  PRIZE_3: '🥉',
  STEP_1: '🥇',
  STEP_2: '🥈',
  STEP_3: '🥉',

  // --- UTILITY & STATUS EMOJIS ---
  SUCCESS: '✅',
  ENABLED: '✅',
  DISABLED: '❌',
  WARNING: '⚠️',
  ERROR: '❌',
  REMOVE: '❌',
  INFO: 'ℹ️',
  info: 'ℹ️',
  CUSTOM_INFO: 'ℹ️',
  LOADING: '🔄',
  UNLOCK: '🔓',
  HIDE: '👁️',
  UNHIDE: '👁️',
  BOOST: '🚀',
  BOOST_GIF: '🚀',
  COUNT: '📊',
  count: '📊',
  MEMBERCOUNT: '👥',
  membercount: '👥',
  COUNTER: '📊',
  RANK: '⭐',
  rank: '⭐',
  INVITELINK: '🔗',
  invitelink: '🔗',
  INVITES: '🔗',
  invites: '🔗',

  // --- LOWERCASE & CAMELCASE ALIASES FOR ECONOMY & COMMANDS ---
  GEAR: '⚙️',
  gear: '⚙️',
  error: '❌',
  success: '✅',
  warning: '⚠️',
  coin: '🪙',
  COIN: '🪙',
  BUILDCOIN: '🪙',
  buildcoin: '🪙',
  money: '💰',
  cash: '💰',
  MONEY: '💰',
  bank: '🏦',
  gem: '💎',
  fire: '🔥',
  wallet: '👛',
  hourglass: '⏳',
  sparkle: '✨',
  tools: '🔧',
  arrowUp: '📈',

  // --- GIVEAWAYS & ECONOMY ---
  GIVEAWAY_PING: '🎉',
  giveaway_ping: '🎉',
  GOLD_CUP: '🏆',
  gold_cup: '🏆',
  SHOP: '🛒',
  shop: '🛒',
  BUY: '🛍️',
  buy: '🛍️',
  SELL: '💵',
  sell: '💵',
  BITCOIN: '🪙',
  bitcoin: '🪙',
  crypto: '🪙',
  PICKAXE: '⛏️',
  pickaxe: '⛏️',
  mine: '⛏️',
  RULERS_CARD: '💳',
  rulers_card: '💳',
  card: '💳',
  networth: '💰',
  NETWORTH: '💰',
  chart: '📊',
  CHART: '📊',
  CELEBRATION: '🎉',
  CHAKRA_SPARK: '✨',
  KABOOM: '💥',
  LEAF: '🍃',
  MESSAGES: '💬',
  STAR: '⭐',
  REFRESH: '🔄',
  RESET: '🔄',
  cache: '🔄',
  detective: '🕵️',
  levelup: '📈',
  pet: '🐾',
  police: '🚨',
  present: '🎁',
  swords: '⚔️',
  target: '🎯',
  trophy: '🏆',
  work: '💼',
  BOT: '🤖',
  AUTOREACT: '🤖',
  CROSS: '❌',
  cross: '❌',
  CROSS_MENU: '❌',
  HOME: '🏠',
  home: '🏠',
  HOME_MENU: '🏠',
  CRYSTAL_BALL: '🔮',
  crystal_ball: '🔮',
  oracle: '🔮',
  DICE: '🎲',
  dice: '🎲',
  MEDITATE: '💤',
  meditate: '💤',
  chakra: '✨',
  NINJA_RANK: '🍥',
  ninja_rank: '🍥',
  RYO: '🪙',
  ryo: '🪙',
  currency: '🪙',
  HAMMER: '🔨',
  hammer: '🔨',
  NINJA_SCROLL: '📜',
  ninja_scroll: '📜',

  // --- MODULE CATEGORY EMOJIS ---
  ALL_MODULES: '📑',
  ANALYTICS_ZAP: '📊',
  ANTINUKE: '🛡️',
  AUTOMOD: '🤖',
  AUTORESPOND: '💬',
  BACKUP: '💾',
  CHANNEL_MOD: '💬',
  FUN: '🎭',
  GIVEAWAY: '🎁',
  LEVEL: '⭐',
  MOD: '🔨',
  MODMAIL_ENVELOPE: '📬',
  MUSIC: '🎶',
  NINJUTSU: '🍥',
  PRIORITY: '⚡',
  SPARKLES: '✨',
  LAPTOP: '💻',
  PROFILE: '👤',
  REACTIONROLES: '🎭',
  SPECIAL_ROLES: '👑',
  STICKY: '📌',
  TICKETS: '🎟️',
  VOICE: '🔊',
  WELCOME: '👋',
  ROLES: '👑',

  // --- ACTIVITY & STATS ---
  ZAP: '⚡',
  STATS: '📊',
  STATS_NEW: '📊',
  SHIELD: '🛡️',
  TOOLS: '🔧',

  // --- ANTINUKE CONTROL PANEL EMOJIS ---
  AN_WHITELIST: '👤',
  AN_WEBHOOK: '🔗',
  AN_SPAM: '🚨',
  AN_SHIELD: '🛡️',
  AN_ROLE: '👑',
  AN_RAID: '⚠️',
  AN_QUARANTINE: '🔒',
  AN_PANIC: '💥',
  AN_KICK: '👞',
  AN_JOINGATE: '🚪',
  AN_GUILD: '🏠',
  AN_CHANNEL: '💬',
  AN_BOT: '🤖',
  AN_BAN: '🔨',

  // --- MUSIC PLAYER EMOJIS ---
  AN_VOLUME: '🔊',
  AN_STOP: '⏹️',
  AN_STAR: '⭐',
  AN_SKIP: '⏭️',
  AN_SHUFFLE: '🔀',
  AN_PREV: '⏮️',
  AN_LYRICS: '📜',
  AN_FAVORITE: '❤️',
  AN_AUTOPLAY: '🔄',
  AN_CLEAR: '🧹',
  AN_LOOP: '🔁',

  // --- AUDIO FILTER EMOJIS ---
  AN_VAPORWAVE: '🌊',
  AN_RESET_FILTER: '🔄',
  AN_NIGHTCORE: '⚡',
  AN_BASSBOOST: '🔊',
  AN_8D_AUDIO: '🎧',

  // --- OBJECT ALIASES FOR BUTTONS & SELECT MENUS ---
  OBJ_ALL_MODULES: '📑',
  OBJ_ANALYTICS: '📊',
  OBJ_ANTINUKE: '🛡️',
  OBJ_AUTOMOD: '🤖',
  OBJ_AUTORESPOND: '💬',
  OBJ_BACKUP: '💾',
  OBJ_CHANNEL_MOD: '💬',
  OBJ_FUN: '🎭',
  OBJ_GIVEAWAY: '🎁',
  OBJ_LEVEL: '⭐',
  OBJ_RANK: '⭐',
  OBJ_INVITELINK: '🔗',
  OBJ_INVITES: '🔗',
  OBJ_INVITE: '🔗',
  OBJ_MOD: '🔨',
  OBJ_MODMAIL: '📬',
  OBJ_MUSIC: '🎶',
  OBJ_NINJUTSU: '🍥',
  OBJ_PRIORITY: '⚡',
  OBJ_PROFILE: '👤',
  OBJ_REACTIONROLES: '🎭',
  OBJ_SPECIAL_ROLES: '👑',
  OBJ_STICKY: '📌',
  OBJ_TICKETS: '🎟️',
  OBJ_VOICE: '🔊',
  OBJ_WELCOME: '👋',
  OBJ_SPLASH: '✨',
  OBJ_REFRESH: '🔄',
  OBJ_OVERVIEW: '📊',
  OBJ_ICON: '🖼️',
  OBJ_FEATURES: '⚡',
  OBJ_EMOJIS: '🎭',
  OBJ_CHANNELS: '💬',
  OBJ_BANNER: '🖼️',
  OBJ_ROLES: '👑',
  OBJ_INFO: 'ℹ️',
  OBJ_PREMIUM: '💎',
  OBJ_ZAP: '⚡',
  OBJ_TOOLS: '🔧',
  OBJ_GEAR: '⚙️',
  OBJ_SHIELD: '🛡️',
  OBJ_NARUTO: '🍥',
  OBJ_OWNER: '👑',
  OBJ_HOME: '🏠',
  OBJ_REMOVE: '❌',
  OBJ_CROSS: '❌',
  OBJ_HAMMER: '🔨',
  OBJ_SCROLL: '📜',
  OBJ_DICE: '🎲',
  OBJ_MEDITATE: '💤',
  OBJ_CRYSTAL_BALL: '🔮',
  OBJ_NINJA_RANK: '🍥',
  OBJ_RYO: '🪙',
  OBJ_ENABLED: '✅',
  OBJ_SUCCESS: '✅',
  OBJ_DISABLED: '❌',
  OBJ_ERROR: '❌',
  OBJ_WARNING: '⚠️',
  OBJ_PANIC: '💥',
  OBJ_STATS: '📊',
  OBJ_MESSAGES: '💬',
  OBJ_AN_WHITELIST: '👤',
  OBJ_AN_WEBHOOK: '🔗',
  OBJ_AN_SPAM: '🚨',
  OBJ_AN_SHIELD: '🛡️',
  OBJ_AN_ROLE: '👑',
  OBJ_AN_RAID: '⚠️',
  OBJ_AN_QUARANTINE: '🔒',
  OBJ_AN_PANIC: '💥',
  OBJ_AN_KICK: '👞',
  OBJ_AN_JOINGATE: '🚪',
  OBJ_AN_GUILD: '🏠',
  OBJ_AN_CHANNEL: '💬',
  OBJ_AN_BOT: '🤖',
  OBJ_AN_BAN: '🔨',
  OBJ_AN_SPARKLES: '✨',
  OBJ_AN_LAPTOP: '💻',
  OBJ_AN_VOLUME: '🔊',
  OBJ_AN_STOP: '⏹️',
  OBJ_AN_STAR: '⭐',
  OBJ_AN_SKIP: '⏭️',
  OBJ_AN_SHUFFLE: '🔀',
  OBJ_AN_PREV: '⏮️',
  OBJ_AN_LYRICS: '📜',
  OBJ_AN_FAVORITE: '❤️',
  OBJ_AN_AUTOPLAY: '🔄',
  OBJ_AN_CLEAR: '🧹',
  OBJ_AN_LOOP: '🔁',
  OBJ_AN_VAPORWAVE: '🌊',
  OBJ_AN_RESET_FILTER: '🔄',
  OBJ_AN_NIGHTCORE: '⚡',
  OBJ_AN_BASSBOOST: '🔊',
  OBJ_AN_8D_AUDIO: '🎧',
  OBJ_LOCK: '🔒',
  OBJ_UNLOCK: '🔓',
  OBJ_HIDE: '👁️',
  OBJ_HUMAN: '👤',
  OBJ_BOT: '🤖',
  OBJ_ROCKET: '🚀'
};

function resolveEmojiForReaction(client, guild, rawEmoji) {
  if (!rawEmoji) return null;
  return rawEmoji.trim();
}

module.exports.resolveEmojiForReaction = resolveEmojiForReaction;
